Fixup pieces of the build

diff --git a/script/verify-build b/script/verify-build
--- a/script/verify-build
+++ b/script/verify-build
@@ -1,4 +1,4 @@
-#/usr/bin/env bash
+#!/bin/bash
 
 # a flag used to tell if the build failed
 fails=""
@@ -14,7 +14,7 @@ if [ "$GOFMT_RESULTS" ]; then
 fi
 
 # Make sure every file has the same license
-LICENSE_RESULTS=`./script/check_license`
+LICENSE_RESULTS=`./script/check-license`
 if [ $? -ne 0 ]; then
 	echo "Not all files have the same license file: "
 	echo "$LICENSE_RESULTS"
@@ -24,9 +24,22 @@ fi
 # Lastly, make sure calling ./query/build.sh doesn't cause ./query/language.peg.go to change
 
 before=$(cat ./query/parser/language.peg.go)
-./query/build.sh
+./query/parser/build.sh
+if [ $? -ne 0 ]; then
+	echo "Not able to rebuild the parser"
+	fails="fails"
+fi
 # we have to reformat in case peg.go produces unformatted code
 gofmt -w ./query/parser/language.peg.go
+if [ $? -ne 0 ]; then
+	echo "Unable to run gofmt on query/parser/language.peg.go"
+	fails="fails"
+fi
+goimports -w query/parser/language.peg.go
+if [ $? -ne 0 ]; then
+	echo "Unable to run goimports on query/parser/language.peg.go"
+	fails="fails"
+fi
 after=$(cat ./query/parser/language.peg.go)
 
 if [ "$before" != "$after" ]; then
